/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * Picky AI Agent
 * Picky AI Agent REST API
 * OpenAPI spec version: 0.1.0
 */
import type {
  HandlerErrorSchema,
  Profile,
  UpdateProfile
} from '../pickyAIAgent.schemas';

import { fetchClient } from '../../fetch-client';

/**
 * Update an existing user profile. Only provided fields are changed.
 * @summary Update a profile
 */
export type handlerResponse200 = {
  data: Profile
  status: 200
}

export type handlerResponse400 = {
  data: HandlerErrorSchema
  status: 400
}

export type handlerResponse404 = {
  data: HandlerErrorSchema
  status: 404
}

export type handlerResponse500 = {
  data: HandlerErrorSchema
  status: 500
}
    
export type handlerResponseSuccess = (handlerResponse200) & {
  headers: Headers;
};
export type handlerResponseError = (handlerResponse400 | handlerResponse404 | handlerResponse500) & {
  headers: Headers;
};

export type handlerResponse = (handlerResponseSuccess | handlerResponseError)

export const getHandlerUrl = (id: string,) => {


  

  return `/api/v1/profile/${id}`
}

export const handler = async (id: string,
    updateProfile: UpdateProfile, options?: RequestInit): Promise<handlerResponse> => {
  
  return fetchClient<handlerResponse>(getHandlerUrl(id),
  {      
    ...options,
    method: 'PUT',
    headers: { 'Content-Type': 'application/json', ...options?.headers },
    body: JSON.stringify(
      updateProfile,)
  }
);}


