/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * Picky API
 * REST API for the Picky AI shopping assistant.
 * OpenAPI spec version: 1.0.0
 */
import type {
  HandlerErrorSchema,
  RecipeResponse
} from '../pickyAPI.schemas';

import { fetchClient } from '../../fetch-client';

/**
 * Returns all recipes with their resolved ingredients. Optionally filter by region.
 * @summary List recipes with ingredients
 */
export type listResponse200 = {
  data: RecipeResponse[]
  status: 200
}

export type listResponse500 = {
  data: HandlerErrorSchema
  status: 500
}
    
export type listResponseSuccess = (listResponse200) & {
  headers: Headers;
};
export type listResponseError = (listResponse500) & {
  headers: Headers;
};

export type listResponse = (listResponseSuccess | listResponseError)

export const getListUrl = () => {


  

  return `/api/v1/recipes`
}

export const list = async ( options?: RequestInit): Promise<listResponse> => {
  
  return fetchClient<listResponse>(getListUrl(),
  {      
    ...options,
    method: 'GET'
    
    
  }
);}


