/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * Picky AI Agent
 * Picky AI Agent REST API
 * OpenAPI spec version: 0.1.0
 */
export interface ChatRequest {
  message: string;
}

export type CreateProfilePreferences = null | Preferences;

/**
 * Request body for creating a new profile.
 */
export interface CreateProfile {
  /** Number of adults in the household. */
  adults?: number;
  /** Budget level (e.g. "budget", "moderate", "flexible"). */
  budget?: string;
  /** Number of cats in the household. */
  cats?: number;
  /** Cooking time preference (e.g. "quick", "moderate", "enthusiast"). */
  cooking_time?: string;
  /** Preferred cuisine types. */
  cuisines?: string[];
  /** Number of dogs in the household. */
  dogs?: number;
  /** The user's email address. */
  email: string;
  /** Health goal (e.g. "balanced", "mediterranean", "high-protein"). */
  health_goal?: string;
  /** Number of kids in the household. */
  kids?: number;
  /** The user's password. */
  password: string;
  preferences?: CreateProfilePreferences;
  /** Dietary restrictions. */
  restrictions?: string[];
}

/**
 * The URI of the endpoint where the problem occurred.

Included when the server can identify the specific resource that caused
the error. Omitted otherwise.
 */
export type HandlerErrorSchemaInstance = string | null;

/**
 * A server-side log reference for this error occurrence.

When present, include this ID in any support request so the error
can be located in server logs. Only set for unexpected server errors.
 */
export type HandlerErrorSchemaLogId = string | null;

/**
 * A structured error response following [RFC 9457 Problem Details](https://www.rfc-editor.org/rfc/rfc9457).

All error responses from this API use this shape with
`Content-Type: application/problem+json`.

## Example

```json
{
  "type": "about:blank",
  "title": "Unauthorized",
  "detail": "You are not authorized to access this resource.",
  "instance": "/api/v1/me",
  "log_id": "01948a62-f94e-7d36-b5ef-70a9b764b2e0"
}
```
 */
export interface HandlerErrorSchema {
  /** A human-readable explanation of this specific occurrence of the problem. */
  detail: string;
  /** Additional structured data specific to this error type.

Only present on errors that carry extra context beyond the standard
fields. Omitted on all standard error responses. */
  extension: unknown;
  /** The URI of the endpoint where the problem occurred.

Included when the server can identify the specific resource that caused
the error. Omitted otherwise. */
  instance?: HandlerErrorSchemaInstance;
  /** A server-side log reference for this error occurrence.

When present, include this ID in any support request so the error
can be located in server logs. Only set for unexpected server errors. */
  log_id?: HandlerErrorSchemaLogId;
  /** A short, stable summary of the problem type.

Does not change between occurrences of the same error kind. */
  title: string;
  /** A URI that identifies the problem type.

Dereferences to human-readable documentation when available.
Defaults to `about:blank` when no specific documentation exists. */
  type: string;
}

/**
 * Request body for logging in.
 */
export interface LoginRequest {
  /** The user's email address. */
  email: string;
  /** The user's password. */
  password: string;
}

/**
 * Input features for a food-preference prediction.
 */
export interface PredictFeatures {
  /** Whether the food is salty (0.0 or 1.0). */
  salty: number;
  /** Whether the food is spicy (0.0 or 1.0). */
  spicy: number;
  /** Whether the food is sweet (0.0 or 1.0). */
  sweet: number;
  /** Whether the food is warm (0.0 or 1.0). */
  warm: number;
}

/**
 * Output of a food-preference prediction.
 */
export interface PredictOutput {
  /** Raw predicted class label (0 = dislike, 1 = like). */
  label: number;
  /** Whether the user is predicted to like the food. */
  liked: boolean;
}

/**
 * Ingredient preference scores (0–100).
 */
export interface Preferences {
  /**
   * Preference score for beef (0–100).
   * @minimum 0
   * @maximum 100
   */
  beef: number;
  /**
   * Preference score for dairy (0–100).
   * @minimum 0
   * @maximum 100
   */
  dairy: number;
  /**
   * Preference score for fish (0–100).
   * @minimum 0
   * @maximum 100
   */
  fish: number;
  /**
   * Preference score for pork (0–100).
   * @minimum 0
   * @maximum 100
   */
  pork: number;
  /**
   * Preference score for spicy food (0–100).
   * @minimum 0
   * @maximum 100
   */
  spicy: number;
}

/**
 * A user profile as returned by the API.
 */
export interface Profile {
  /** Number of adults in the household. */
  adults: number;
  /** Budget level (e.g. "budget", "moderate", "flexible"). */
  budget: string;
  /** Number of cats in the household. */
  cats: number;
  /** Cooking time preference (e.g. "quick", "moderate", "enthusiast"). */
  cooking_time: string;
  /** Preferred cuisine types. */
  cuisines: string[];
  /** Number of dogs in the household. */
  dogs: number;
  /** The user's email address. */
  email: string;
  /** Health goal (e.g. "balanced", "mediterranean", "high-protein"). */
  health_goal: string;
  /** The unique identifier for the profile. */
  id: string;
  /** Number of kids in the household. */
  kids: number;
  /** Ingredient preference scores. */
  preferences: Preferences;
  /** Dietary restrictions. */
  restrictions: string[];
}

/**
 * Number of adults in the household.
 */
export type UpdateProfileAdults = number | null;

/**
 * Budget level.
 */
export type UpdateProfileBudget = string | null;

/**
 * Number of cats in the household.
 */
export type UpdateProfileCats = number | null;

/**
 * Cooking time preference.
 */
export type UpdateProfileCookingTime = string | null;

/**
 * Preferred cuisine types.
 */
export type UpdateProfileCuisines = string[] | null;

/**
 * Number of dogs in the household.
 */
export type UpdateProfileDogs = number | null;

/**
 * The user's email address.
 */
export type UpdateProfileEmail = string | null;

/**
 * Health goal.
 */
export type UpdateProfileHealthGoal = string | null;

/**
 * Number of kids in the household.
 */
export type UpdateProfileKids = number | null;

/**
 * The user's password.
 */
export type UpdateProfilePassword = string | null;

export type UpdateProfilePreferences = null | Preferences;

/**
 * Dietary restrictions.
 */
export type UpdateProfileRestrictions = string[] | null;

/**
 * Request body for updating an existing profile (all fields optional).
 */
export interface UpdateProfile {
  /** Number of adults in the household. */
  adults?: UpdateProfileAdults;
  /** Budget level. */
  budget?: UpdateProfileBudget;
  /** Number of cats in the household. */
  cats?: UpdateProfileCats;
  /** Cooking time preference. */
  cooking_time?: UpdateProfileCookingTime;
  /** Preferred cuisine types. */
  cuisines?: UpdateProfileCuisines;
  /** Number of dogs in the household. */
  dogs?: UpdateProfileDogs;
  /** The user's email address. */
  email?: UpdateProfileEmail;
  /** Health goal. */
  health_goal?: UpdateProfileHealthGoal;
  /** Number of kids in the household. */
  kids?: UpdateProfileKids;
  /** The user's password. */
  password?: UpdateProfilePassword;
  preferences?: UpdateProfilePreferences;
  /** Dietary restrictions. */
  restrictions?: UpdateProfileRestrictions;
}

