/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * Picky API
 * REST API for the Picky AI shopping assistant.
 * OpenAPI spec version: 1.0.0
 */
import type {
  HandlerErrorSchema,
  HandlerParams,
  RecommendResponse
} from '../pickyAPI.schemas';

import { fetchClient } from '../../fetch-client';

/**
 * Given a profile ID, compute the user embedding via the two-tower ONNX model and return the top-k nearest meals from Qdrant.
 * @summary Get meal recommendations
 */
export type handlerResponse200 = {
  data: RecommendResponse
  status: 200
}

export type handlerResponse400 = {
  data: HandlerErrorSchema
  status: 400
}

export type handlerResponse404 = {
  data: HandlerErrorSchema
  status: 404
}

export type handlerResponse500 = {
  data: HandlerErrorSchema
  status: 500
}

export type handlerResponse503 = {
  data: HandlerErrorSchema
  status: 503
}
    
export type handlerResponseSuccess = (handlerResponse200) & {
  headers: Headers;
};
export type handlerResponseError = (handlerResponse400 | handlerResponse404 | handlerResponse500 | handlerResponse503) & {
  headers: Headers;
};

export type handlerResponse = (handlerResponseSuccess | handlerResponseError)

export const getHandlerUrl = (profileId: string,
    params?: HandlerParams,) => {
  const normalizedParams = new URLSearchParams();

  Object.entries(params || {}).forEach(([key, value]) => {
    
    if (value !== undefined) {
      normalizedParams.append(key, value === null ? 'null' : value.toString())
    }
  });

  const stringifiedParams = normalizedParams.toString();

  return stringifiedParams.length > 0 ? `/api/v1/recommend/${profileId}?${stringifiedParams}` : `/api/v1/recommend/${profileId}`
}

export const handler = async (profileId: string,
    params?: HandlerParams, options?: RequestInit): Promise<handlerResponse> => {
  
  return fetchClient<handlerResponse>(getHandlerUrl(profileId,params),
  {      
    ...options,
    method: 'GET'
    
    
  }
);}


